version: "3.1"

services:
  dbhost:
    container_name: prod_goudendraak
    image: mysql:5.7
    restart: on-failure
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: prod_goudendraak
      MYSQL_USER: prod_goudendraak
      MYSQL_PASSWORD: prod_goudendraak
      MYSQL_ROOT_PASSWORD: prod_goudendraak
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d:ro
  # Redis Server for Cache
  redis-cache:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
